[package]
name = "api_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = "0.2.0"
serde = "1.0.137"
serde_json = "1.0.81"
serde_derive = "1.0.137"
actix-web = "4.0.1"
hyper = "0.14.19"